from flask import Flask, render_template, request, flash, redirect, url_for, session
from flaskext.mysql import MySQL
import os
import time
import numpy as np
import pandas as pd

app = Flask(__name__, template_folder='templates')
app.config['SESSION_TYPE']= 'memcached'
app.config['SECRET_KEY']= 'super secret key'
db = MySQL()

app.config['MYSQL_DATABASE_USER'] = 'root'
app.config['MYSQL_DATABASE_PASSWORD'] = 'hello123'
app.config['MYSQL_DATABASE_DB'] = 'CS660_webapp'
app.config['MYSQL_DATABASE_HOST'] = '127.0.0.1'
db.init_app(app)

conn = db.connect()
cursor = conn.cursor()


@app.route('/', methods=['POST', 'GET'])
def home():

    #when user is not signed in

    query = 'SELECT album_name FROM albums'
    cursor.execute(query)
    all_albums = []
    for album in cursor:
        all_albums.append(album[0])
    return render_template('index.html', albums=all_albums)

@app.route('/login_page', methods=['POST', 'GET'])
def login_page(message='Please Log In'):
    return render_template('login_page.html', message=message)

@app.route('/signup_page', methods=['POST', 'GET'])
def signup_page(message="Please complete the form to sign up"):
    return render_template('signup_page.html', message=message)

@app.route('/signup', methods=['POST','GET'])
def signup():                             #signup function

    #test password mismatch

    result = request.form
    if result['password1'] != result['password2']:
        return signup("Password Mismatch")
    #need other input checks here (like those in mysql)



    #test account already exists

    email=result['email']
    query = 'SELECT email FROM users'
    cursor.execute(query)
    for item in cursor:
        if item[0] == email:         #item[0] is the email attribute of the user
            return login_page("You may already have an account - please log in")

    #insert data into database

    session['email'] = email
    query = 'INSERT INTO users(email, password, first_name, ' \
            'last_name, DoB, hometown, gender) VALUES (%s, %s, %s, %s, %s, %s, %s)'
    DoB = time.strptime(result['DoB'], '%Y-%m-%d')

    #exception handling here is for potential errors from database insertion

    try:
        cursor.execute(query,
                   (result['email'], result['password1'], result['first_name'], result['last_name'],
                    time.strftime('%Y-%m-%d %H:%M:%S', DoB), result['hometown'], result['gender']))
    except:
        return signup_page("Oops, something went wrong - please try again")

    #get id generated by database upon insertion

    query = 'SELECT user_id, email, first_name FROM users'
    cursor.execute(query)
    for item in cursor:
        if result['email'] == item[1]:
            userid = item[0]
            my_name = item[2]
            break

    session['userid'] = userid
    session['my_name'] = my_name
    return view_profile(id=userid)



@app.route('/login', methods=['POST', 'GET'])
def login():

    result = request.form
    email = result['email']
    password = result['password']

    #check user has account
    query = 'SELECT email, password, user_id, first_name FROM users'
    cursor.execute(query)
    if cursor.rowcount == 0:
        return signup_page("No Account with this email and password, would you like to create an account?")

    #check password match
    for item in cursor:
        if item[0] == email:
            if item[1] == password:
                session['userid'] = item[2]
                session['my_name'] = item[3]
                return view_profile(id=item[2])
            else:
                return login_page('Wrong Password')

    return signup("No Account with this email and password, would you like to create an account?")

@app.route('/logout', methods=['GET', 'POST'])
def logout():
    session.clear()
    return home()

@app.route('/view_profile/<id>', methods=['POST', 'GET'])
def view_profile(id):

    #get name of the person who's profile you're viewing

    query = 'SELECT user_id, first_name FROM users'
    cursor.execute(query)
    for item in cursor:
        if id == item[0]:
            person_name = item[1]

    #if you're logged in

    if session.get('userid', None):

        #get my name

        userid = session.get('userid', None)
        my_name = session.get('my_name', None)

        if int(userid) == int(id):
            return render_template('profile.html', name=person_name, username=my_name, loggedin=True,
                                   myprofile=True, userid=userid, id= id)
        else:
            return render_template('profile.html', name=person_name, username=my_name, loggedin=True,
                                   myprofile=False, userid=userid, id=id)

    return render_template('profile.html', name=person_name, loggedin=False, myprofile=False, id=id)


@app.route('/upload', methods=['GET', 'POST'])
def upload():
    userid = session.get('userid', None)
    my_name = session.get('my_name', None)
    return render_template('upload.html', name=my_name, id=userid)

@app.route('/create_album', methods=['GET', 'POST'])
def create_album():
    userid = session.get('userid', None)
    my_name = session.get('my_name', None)

    #insert into database album and content
    result = request.form
    query = 'INSERT INTO albums(user_id, album_name, DOC) VALUES (%s, %s, %s)'
    DoC = '2017-10-10'
    cursor.execute(query, (userid, result['album'], DoC))

    query = 'SELECT album_name, user_id FROM albums'
    cursor.execute(query)
    all_albums = []
    for album in cursor:
        if album[1] == userid:
            all_albums.append(album[0])

    return render_template('albums.html', name=my_name, albums=all_albums)


@app.route('/albums/<id>', methods=['GET', 'POST'])
def albums(id):

    try:
        id = session.get('userid', None)
        if id:
            query = 'SELECT user_id, first_name FROM users'
            cursor.execute(query)
            for user in cursor:
                if user[0] == session.get('userid', None):
                    fname = user[1]

            query = 'SELECT album_name, user_id FROM albums'
            cursor.execute(query)
            all_albums = []
            for album in cursor:
                if album[1] == session.get('userid', None):
                    all_albums.append(album[0])

        return render_template('albums.html', name=fname, albums=all_albums, loggedin=True)

    except:
        query = 'SELECT user_id, first_name FROM users'
        cursor.execute(query)
        for user in cursor:
            if user[1] == username:
                userid = user[0]

        query = 'SELECT album_name, user_id FROM albums'
        cursor.execute(query)
        all_albums = []
        for album in cursor:
            if album[1] == userid:
                all_albums.append(album[0])

        return render_template('albums.html', albums=all_albums, loggedin=False)






@app.route('/visit', methods=['GET', 'POST'])
def visit():
    return render_template('visit.html')


@app.route('/photo_search', methods=['GET', 'POST'])
def photo_search():
    return render_template('photo_search.html')



@app.route('/album_photos/<album_name>', methods=['GET', 'POST'])
def album_photos(data=None, album_name=""):
    query = 'SELECT album_name, user_id FROM albums'
    cursor.execute(query)
    for album in cursor:
        if album_name == album[0]:
            userid = album[1]
            break

    query = 'SELECT user_id, first_name FROM users'
    cursor.execute(query)
    for item in cursor:
        if item[0] == userid:
            username = item[1]
            break

    try:
        id = session.get('userid', None)
        if id:
            query = 'SELECT user_id, first_name FROM users'
            cursor.execute(query)
            for user in cursor:
                if user[0] == session.get('userid', None):
                    fname = user[1]

            return render_template('photos.html', data=data, album_name=album_name,
                                   name=fname, username=username,
                                   loggedin=session.get('loggedin', None))
    except:
        return render_template('photos.html', data=data, album_name=album_name,
                               username=username, loggedin=False)


@app.route('/comment', methods=['GET', 'POST'])
def comment():
    nc = request.form['newcomment']
    return render_template('single_photo.html', comments=[session.get('email', None).split('@')[0], nc])


@app.route('/friend_search', methods=['GET', 'POST'])
def friend_search():
    return render_template('friendsearch.html', name=session.get('email', None).split('@')[0])

@app.route('/search', methods=['GET', 'POST'])
def search():
    return render_template('search.html', name=session.get('email', None).split('@')[0])

@app.route('/friends', methods=['GET', 'POST'])
def friends():
    return render_template('friends.html', name=session.get('email', None).split('@')[0])


@app.route('/friend_add', methods=['GET', 'POST'])
def friend_add(friend):
    return render_template('friend_add.html', name=session.get('email', None).split('@')[0], friend=friend)

@app.route('/friend_delete', methods=['GET', 'POST'])
def friend_delete():
    return render_template('friend_delete.html', name=session.get('email', None).split('@')[0])

@app.route('/friend_list', methods=['GET', 'POST'])
def friend_list():
    return render_template('friend_list.html', name=session.get('email', None).split('@')[0])


@app.route('/people_search', methods=['GET', 'POST'])
def people_search():
    return render_template('people_search.html')

@app.route('/photo_recommend', methods=['GET', 'POST'])
def photo_recommend():
    return render_template('photo_recommend.html')


if __name__=='__main__':
    app.secret_key = os.urandom(100)
    app.run(debug=True)